### ISSUE TITLE
A small bug has occured

### ISSUE THREAD

**Issue by dmunao** [ebas-submission-tool/troubleshooting#3]
When tying to upload and check a file the following error occurs:

A small bug has occured. We are truly sorry for this. Please check that the file you are trying to parse follows the correct syntax. We are logging this error and will look in to this in the near future. In the mean time, you should be able to use the EBAS Data Submission Tool on the front page (http://ebas-submit-tool.nilu.no/). You could also submit this bug using our issue tracker (https://github.com/ebas-submission-tool/troubleshooting/issues).

**Comment by richard-olav** [comment]
@dmunao it is hard to say what this issue might be, but since the ebas-submit-tool cannot read the file I am guessing it might have something to do with encoding of the file. 

If you could possibly send me the file you are working with, I can have a look?

Please send it to ebas@nilu.no.

**Comment by pauleckhardt** [comment]
Hi David and  Richard!

I looked into this. It was a bug in the core ebas software. Fixed it now.
I'll try to roll this out to the submit-tool today.

By the way, the reason was that the file was header only (no data lines).

**Comment by dmunao** [comment]
Hi Paul,

did you manage to update the submission tool on the NILU website?

Today I am receiving the error again while trying to check the SMPS level 1 header file.

Let me know!

David.

**Comment by pauleckhardt** [comment]
Hi David,

I updated it yesterday and sent you a message to your support request (ebas@nilu.no).
I just tried the file you sent yesterday, and it still works.

Can you send me the file you have problems with today? Please reply to the support system mail, then it's attached to the sam,e support case.

Paul

**Comment by pauleckhardt** [comment]
INFO: found another bug, fixed and rolled out 2016-01-19T10:17:00
