### ISSUE TITLE
Error while uploading DMPS level 0 and 1 files

### ISSUE THREAD

**Issue by markusfiebig** [ebas-submission-tool/troubleshooting#6]
I received an error while uploading the attached files.
[NO0002R.20170101000000.20180426184101.particle_number_size_distribution.pm10.1y.357s.lev1a.nas.gz](https://github.com/ebas-submission-tool/troubleshooting/files/2090499/NO0002R.20170101000000.20180426184101.particle_number_size_distribution.pm10.1y.357s.lev1a.nas.gz)
[NO0002R.20170101000000.20180424190927.particle_number_size_distribution.pm10.1y.357s.lev0a.nas.gz](https://github.com/ebas-submission-tool/troubleshooting/files/2090500/NO0002R.20170101000000.20180424190927.particle_number_size_distribution.pm10.1y.357s.lev0a.nas.gz)

**Comment by markusfiebig** [comment]
Of course, the files were uploaded uncompressed.

**Comment by pauleckhardt** [comment]
Thanks for the report. This was due tu an unknown data level and additionally a code bug when generating the error message. Both problems are fixed now.
